# Generated by Django 6.0.5 on 2026-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_contacto',
            field=models.DateTimeField(),
        ),
    ]
